### ISSUE TITLE
/usr/local/bin/fetch: line 35: type: : not found

### ISSUE THREAD

**Issue by voxie12** [Manas140/fetch#3]
![maim-window-20220114-170010](https://user-images.githubusercontent.com/65469239/149555108-4821b88a-9847-4103-b8aa-a840cdb9e3c1.png)

how to fix it?

**Comment by Manas140** [comment]
which wm are you actually running?

**Comment by Manas140** [comment]
check if it works now with the latest update.

**Comment by voxie12** [comment]
> which wm are you actually running?

sorry for not answering. i use dwm

> check if it works now with the latest update.

it works perfectly well! thank you.
