### ISSUE TITLE
Error when multiple terminals open up

### ISSUE THREAD

**Issue by Spaxly** [Manas140/fetch#6]
The error shown below occurs when you launch a terminal. This can be opening up multiple instances of the terminal with the script running at startup or opening one instance. I don't know why this is happening, especially when its randomly.

/usr/local/bin/fetch: line 41: /proc/2202644/comm: No such file or directory

**Comment by Manas140** [comment]
well i tried to add

```/usr/local/bin/fetch -d ``` 

in my `.zshrc` though I'm unable to recreate the problem...

also the error shows that it's a problem while fetching the Wm, and I've never seen a number that big in `/proc`

I'd also like to have a screenshot of the issue

**Comment by Spaxly** [comment]
![eeee](https://user-images.githubusercontent.com/68564017/211898715-632381f5-f05c-4131-977b-7616a2d6c6e9.png)
Here's a screenshot of the error.

**Comment by Manas140** [comment]
Well that shouldn't be happening though try adding
```      [ -f "$i" ] || continue```
on line 41 before

**Comment by Spaxly** [comment]
I think that fixed the issue, thanks.
